### PR TITLE
Many changes

### PR DESCRIPTION
**Pull request by jerryz123**
Added:
-Qt GUI
-Diverging colormap support, up-down-up, down-up-down, up-up-up
-.JSCM savefiles
-Catmul-clark spline building, which is the new default. The old method remains
-Complete backwards-compatibility
-And more small improvements

### CODE REVIEW

**Comment by jerryz123** [comment]
@stefanv @njsmith

**Comment by stefanv** [comment]
It looks like this version cannot edit existing matplotlib colormaps.  Can we fit a spline to the existing datapoints and display that?

**Comment by jerryz123** [comment]
I thought we decided that this would not be implemented in the next version. There is no clear methodology for how we should fit splines and add control points.

How many control points do we add?
How close do we have to fit the spline?
What do we do when the existing colormap is jagged?

**Comment by stefanv** [comment]
OK, if we discussed it, then it's fine.

I tried to get this branch running on PyQt5 today, but didn't have
much luck :/

**Comment by jerryz123** [comment]
All the code was written for PyQt4, and it requires some tweaks to port to PyQt5. I don't think PyQt5 was released when I was writing this.

I'll get it running in PyQt5.

**Comment by jerryz123** [comment]
@stefanv 
On PyQt5 editing the colormap is very slow. You can try on the other branch, [https://github.com/jerryz123/viscm/tree/pyqt5](https://github.com/jerryz123/viscm/tree/pyqt5)

**Comment by njsmith** [comment]
Finally merged in ae93388ed14fba93c35b9e2dcce1b0d370e68d98!

**Comment by njsmith** [comment]
(Note for future reference: before merging I edited history to get rid of the icon image files that we can't legally use/distribute.)

**Comment by stefanv** [comment]
Thank you for all your hard work, @jerryz123 !

**Pull request closed without merging**
